#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MODELS_DIR="${SCRIPT_DIR}/eflint-models"

REQUESTER="${1:-user@example.com}"
STEWARDS_CSV="${2:-VU}"
OUTPUT_FILE="${3:-${MODELS_DIR}/generated_validation_bundle.eflint}"

if [[ ! -f "${MODELS_DIR}/01_interface_policy.eflint" ]]; then
    echo "Missing ${MODELS_DIR}/01_interface_policy.eflint" >&2
    exit 1
fi

if [[ ! -f "${MODELS_DIR}/02_agreement_rules.eflint" ]]; then
    echo "Missing ${MODELS_DIR}/02_agreement_rules.eflint" >&2
    exit 1
fi

escape_eflint_literal() {
    local input="$1"
    input="${input//\\/\\\\}"
    input="${input//\"/\\\"}"
    printf '%s' "$input"
}

trim() {
    local s="$1"
    s="${s#${s%%[![:space:]]*}}"
    s="${s%${s##*[![:space:]]}}"
    printf '%s' "$s"
}

IFS=',' read -r -a raw_stewards <<< "${STEWARDS_CSV}"

declare -A seen=()
stewards=()
for raw in "${raw_stewards[@]}"; do
    steward="$(trim "${raw}")"
    if [[ -z "${steward}" ]]; then
        continue
    fi
    if [[ -z "${seen[${steward}]+x}" ]]; then
        seen["${steward}"]=1
        stewards+=("${steward}")
    fi
done

if [[ ${#stewards[@]} -eq 0 ]]; then
    echo "No stewards provided. Use a comma-separated list as arg2, e.g. VU,UVA." >&2
    exit 1
fi

mkdir -p "$(dirname "${OUTPUT_FILE}")"

req_escaped="$(escape_eflint_literal "${REQUESTER}")"

{
    echo "// Generated by build-eflint-validation-bundle.sh"
    echo "// requester=${REQUESTER}"
    echo "// stewards=${STEWARDS_CSV}"
    echo ""

    echo "// Layer 1: interface policy"
    cat "${MODELS_DIR}/01_interface_policy.eflint"
    echo ""

    echo "// Layer 2a: shared agreement rules"
    cat "${MODELS_DIR}/02_agreement_rules.eflint"
    echo ""

    echo "// Layer 2b: per-steward agreement files"
    for steward in "${stewards[@]}"; do
        model_file="${MODELS_DIR}/${steward}.eflint"
        if [[ -f "${model_file}" ]]; then
            echo "// steward model: ${steward}"
            cat "${model_file}"
            echo ""
        else
            echo "// steward model missing: ${steward} (${model_file})"
        fi
    done

    echo "// Layer 3: request facts"
    printf '+requester("%s").\n' "${req_escaped}"
    for steward in "${stewards[@]}"; do
        steward_escaped="$(escape_eflint_literal "${steward}")"
        printf '+requested-steward("%s").\n' "${steward_escaped}"
    done
    echo ""

    echo "// Queries used in EvaluateRequestApproval"
    printf '?Holds(permitted-request("%s")).\n' "${req_escaped}"
    for steward in "${stewards[@]}"; do
        steward_escaped="$(escape_eflint_literal "${steward}")"
        printf '?Holds(permitted-at-steward("%s", "%s")).\n' "${req_escaped}" "${steward_escaped}"
        printf '?-archetype When valid-archetype("%s", "%s", archetype).\n' "${req_escaped}" "${steward_escaped}"
        printf '?-compute-provider When valid-compute-provider("%s", "%s", compute-provider).\n' "${req_escaped}" "${steward_escaped}"
    done

    echo ""
    echo "// Acts used in EvaluateRequestApproval"
    echo "// Run submit-data-request only for stewards where permitted-at-steward holds."
    for steward in "${stewards[@]}"; do
        steward_escaped="$(escape_eflint_literal "${steward}")"
        printf '// submit-data-request("%s", "%s").\n' "${req_escaped}" "${steward_escaped}"
    done
} > "${OUTPUT_FILE}"

echo "Wrote ${OUTPUT_FILE}"
